name: Gins-Rime
author: Gins-Rime
version: "0.1"

iphone:
  portrait:
    pinyin: light/pinyin_26_portrait.yaml
    alphabetic: light/alphabetic_26_portrait.yaml
    numeric: light/numeric_9_portrait.yaml
  landscape:
    pinyin: light/pinyin_26_landscape.yaml
    alphabetic: light/alphabetic_26_landscape.yaml
    numeric: light/numeric_9_landscape.yaml
